modified nav bar and added responsive design
axelzo/food-menu pull request #4
Opened 2020-09-21 23:06 UTC by Jomalagon

Responsive design of the img and title was added and the button was changed.

2020-09-22 01:47 UTC, axelzo requested changes
En general todo te quedo excelente, solo deje unos pequeños comentarios.

2020-09-22 01:47 UTC, axelzo commented on style.css
> +.navigation__item_l {
Intenta utilizar la nomenclatura BEM que estamos usando e este proyecto `navigation__item--left` quedaria mejor con la nomenclatura.

2020-09-22 01:47 UTC, axelzo commented on style.css
> +    .imgportada {
Creo que quedaria mejor `.img-portada`

2020-09-22 02:25 UTC, Jomalagon commented on style.css
> +.navigation__item_l {
Ready

2020-09-22 02:25 UTC, Jomalagon commented on style.css
> +    .imgportada {
Ready

2020-09-23 02:55 UTC, axelzo commented
@Jomalagon Thanks! 
Approved.

2020-09-23 02:55 UTC, merged