added  JS file and onclick in HTML
axelzo/food-menu pull request #7
Opened 2020-10-14 20:34 UTC by Jomalagon

@axelzo added JS file with function signin linked onclick at login in navbar.

2020-10-14 23:17 UTC, axelzo requested changes

2020-10-14 23:17 UTC, axelzo commented on scripFoodMenu.js
> +
Avoid extra white space.

2020-10-14 23:17 UTC, axelzo commented on scripFoodMenu.js
> +    // if (user === database[0].username &&
Avoid left commented code.

2020-10-14 23:17 UTC, axelzo commented on scripFoodMenu.js
> +
Avoid extra white space.

2020-10-14 23:17 UTC, axelzo commented on scripFoodMenu.js
> +        username: "petra",
Use Uppercase on `"petra"`.

2020-10-14 23:17 UTC, axelzo commented on index.html
> +        <script type="text/javascript" src="scripFoodMenu.js"></script>
You missed t on `scriptFoodMenu`

2020-10-22 18:18 UTC, Jomalagon commented on scripFoodMenu.js
> +
Ready

2020-10-22 18:19 UTC, Jomalagon commented on scripFoodMenu.js
> +
Ready

2020-10-22 18:21 UTC, Jomalagon commented on index.html
> +        <script type="text/javascript" src="scripFoodMenu.js"></script>
renamed to script.js

2020-10-22 18:56 UTC, closed without merging

2020-10-22 19:01 UTC, Jomalagon commented
@axelzo  I don't know what I did, but better than was if  stay.